### ISSUE TITLE
詳細ページ - 記事最下部に関連記事（サムネールあり）をつける

### ISSUE THREAD

**Issue by ToruTakatoriSun** [sun-asterisk-training/headlesscms-app-boiler-plate#14]
**Is your feature request related to a problem? Please describe.**
Nilto、MicroCMSそれぞれを切り替えても「関連記事」を表示できるようにする機能を実装する必要がある

**Describe the solution you'd like**
北沢さんから「デザイナーの方にデザインを作ってもらっている」と聞いているので、そのデザインを参照したうえで「関連記事」を実装する必要がある。

・関連記事は、ヘッドレスCMSでページ内容を記載する際に差し込めること
・関連記事はシリーズものの想定。関連記事のウィジェットを貼りたい。

**Describe alternatives you've considered**
特に無し

**Additional context**
特に無し

**Comment by shimizu-n7** [comment]
memo
デザインは別チケットを切って対応する。
